# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/images.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/images.proto',
  package='images',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/images.proto\x12\x06images\"\x1c\n\x0cReplyRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1e\n\rReplyResponse\x12\r\n\x05\x66iles\x18\x01 \x01(\t2A\n\x07Gateway\x12\x36\n\x05Reply\x12\x14.images.ReplyRequest\x1a\x15.images.ReplyResponse\"\x00\x62\x06proto3'
)




_REPLYREQUEST = _descriptor.Descriptor(
  name='ReplyRequest',
  full_name='images.ReplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='images.ReplyRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_REPLYRESPONSE = _descriptor.Descriptor(
  name='ReplyResponse',
  full_name='images.ReplyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='images.ReplyResponse.files', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['ReplyRequest'] = _REPLYREQUEST
DESCRIPTOR.message_types_by_name['ReplyResponse'] = _REPLYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplyRequest = _reflection.GeneratedProtocolMessageType('ReplyRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLYREQUEST,
  '__module__' : 'proto.images_pb2'
  # @@protoc_insertion_point(class_scope:images.ReplyRequest)
  })
_sym_db.RegisterMessage(ReplyRequest)

ReplyResponse = _reflection.GeneratedProtocolMessageType('ReplyResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPLYRESPONSE,
  '__module__' : 'proto.images_pb2'
  # @@protoc_insertion_point(class_scope:images.ReplyResponse)
  })
_sym_db.RegisterMessage(ReplyResponse)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='images.Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reply',
    full_name='images.Gateway.Reply',
    index=0,
    containing_service=None,
    input_type=_REPLYREQUEST,
    output_type=_REPLYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
